{% set name = "sagemaker-studio-dataengineering-sessions" %}
{% set version = "1.3.17" %}
{% set python_min = "3.11" %}
{% set sha256 = "bf2d26b0e6bc7caf3b617a5b539b94c9b06e6e88c74daa24603a2ed5a1310e34" %}
{% set blake2b256 = "c0d3fa3b7e4762d894fd6d50809394a387ecb377bf2947884d727cdae1a837c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/2b/0a/c50f898aa998c7ba21645c2479f691f1b090f8e73b0a779d4a01ff5bc403/sagemaker_studio_dataengineering_sessions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - pytest
    - ipython
    - amazon-sagemaker-sql-execution >=0.0.7,<1
    - pandas
    - sqlparse >=0.4.0
    - sparkmagic
    - botocore
    - panel
    - pytest-cov

test:
  imports:
    - sagemaker_studio_dataengineering_sessions
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: A python Package to run Spark code in different AWS Compute
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - yzhum
    - AshleyZSY
    - freddylyu173
    - Jas0nch
