{% set name = "sagemaker-studio-dataengineering-sessions" %}
{% set version = "1.3.4" %}
{% set python_min = "3.11" %}
{% set sha256 = "537e1c6d1ccf99f9aa4d6ed02c5939781d8311cf685242adb21d34c2c2ab2005" %}
{% set blake2b256 = "c0d3fa3b7e4762d894fd6d50809394a387ecb377bf2947884d727cdae1a837c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/25/97/79be77833f37fd55d1df805b05b0e338074c47cb4e40feb3eb304b69bf2b/sagemaker_studio_dataengineering_sessions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - pytest
    - ipython
    - amazon-sagemaker-sql-execution >=0.0.7,<1
    - pandas
    - sqlparse >=0.4.0
    - sparkmagic
    - botocore
    - panel
    - pytest-cov

test:
  imports:
    - sagemaker_studio_dataengineering_sessions
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: A python Package to run Spark code in different AWS Compute
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - yzhum
    - AshleyZSY
    - freddylyu173
    - Jas0nch
