{% set name = "sagemaker-studio-dataengineering-sessions" %}
{% set version = "1.2.5" %}
{% set python_min = "3.11" %}
{% set sha256 = "724b072405d9d74a5f42fcfd7a7fbc415b631e40cc37e03672a282ae8f07339a" %}
{% set blake2b256 = "bf280418efd26f9f08bafb5c0c35a5d3e845d08d21e5272b7b7f4acac8620fe6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/{{ blake2b256[:2] }}/{{ blake2b256[2:4] }}/{{ blake2b256[4:] }}/sagemaker_studio_dataengineering_sessions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - pytest
    - ipython
    - amazon-sagemaker-sql-execution >=0.0.7,<1
    - pandas
    - sqlparse >=0.4.0
    - sparkmagic
    - botocore
    - panel
    - pytest-cov

test:
  imports:
    - sagemaker_studio_dataengineering_sessions
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: A python Package to run Spark code in different AWS Compute
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - AshleyZSY
    - freddylyu173
    - Jas0nch
