{% set name = "sagemaker-studio-dataengineering-sessions" %}
{% set version = "1.3.21" %}
{% set python_min = "3.11" %}
{% set sha256 = "daa05c37c2b2d30daf7c5f061aa0f9b4aef71e0970e24cff12bed33eea0c9cec" %}
{% set blake2b256 = "c0d3fa3b7e4762d894fd6d50809394a387ecb377bf2947884d727cdae1a837c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/20/c2/b2cdb4c0195c52cf33307ea5ff93d6deaf0516983cc9eaa5b90e859398f0/sagemaker_studio_dataengineering_sessions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - pytest
    - ipython
    - amazon-sagemaker-sql-execution >=0.0.7,<1
    - pandas
    - sqlparse >=0.4.0
    - sparkmagic
    - botocore
    - panel
    - pytest-cov

test:
  imports:
    - sagemaker_studio_dataengineering_sessions
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: A python Package to run Spark code in different AWS Compute
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - tchenlin
    - yzhum
    - AshleyZSY
    - freddylyu173
    - Jas0nch
