{% set name = "sagemaker-studio-dataengineering-sessions" %}
{% set version = "1.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker_studio_dataengineering_sessions-{{ version }}.tar.gz
  sha256: 2ae59653fc5af3efee52b7791af65ccdb546ff4eaf8b86ef1854f31e0f988159

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - pytest
    - ipython
    - amazon-sagemaker-sql-execution >=0.0.7,<1
    - pandas
    - sqlparse >=0.4.0
    - sparkmagic
    - botocore
    - panel
    - pytest-cov

test:
  imports:
    - sagemaker_studio_dataengineering_sessions
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: A python Package to run Spark code in different AWS Compute
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - AshleyZSY
    - freddylyu173
    - Jas0nch
